[tool:pytest]
addopts =
    --html=reports/test_report.html
    --self-contained-html
    --capture=no
    --tb=short
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
